# Generated by Django 3.1.3 on 2020-11-11 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='appointment',
            table='appointment_db',
        ),
    ]
