# Generated by Django 3.1.3 on 2020-11-11 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201111_2314'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='appointment',
            table=None,
        ),
    ]
